entity.job_application.settings:
  title: 'Settings'
  route_name: entity.job_application.settings
  base_route: entity.job_application.settings
entity.job_application.view:
  title: 'View'
  route_name: entity.job_application.canonical
  base_route: entity.job_application.canonical
entity.job_application.edit_form:
  title: 'Edit'
  route_name: entity.job_application.edit_form
  base_route: entity.job_application.canonical
entity.job_application.delete_form:
  title: 'Delete'
  route_name: entity.job_application.delete_form
  base_route: entity.job_application.canonical
  weight: 10
entity.job_application.collection:
  title: 'Job Applicationss'
  route_name: entity.job_application.collection
  base_route: system.admin_content
  weight: 10
